if g:dein#_cache_version !=# 230 || g:dein#_init_runtimepath !=# '/home/segas/dotfiles/nvim/dein/bundle/repos/github.com/Shougo/dein.vim/,/home/segas/.config/nvim,/etc/xdg/xdg-ubuntu/nvim,/etc/xdg/nvim,/home/segas/.local/share/nvim/site,/usr/share/ubuntu/nvim/site,/usr/local/share/nvim/site,/usr/share/nvim/site,/var/lib/snapd/desktop/nvim/site,/usr/share/nvim/runtime,/var/lib/snapd/desktop/nvim/site/after,/usr/share/nvim/site/after,/usr/local/share/nvim/site/after,/usr/share/ubuntu/nvim/site/after,/home/segas/.local/share/nvim/site/after,/etc/xdg/nvim/after,/etc/xdg/xdg-ubuntu/nvim/after,/home/segas/.config/nvim/after' | throw 'Cache loading error' | endif
let [plugins, ftplugin] = dein#load_cache_raw(['/home/segas/.config/nvim/init.vim', '/home/segas/dotfiles/nvim/dein/dein.toml', '/home/segas/dotfiles/nvim/dein/dein_lazy.toml'])
if empty(plugins) | throw 'Cache loading error' | endif
let g:dein#_plugins = plugins
let g:dein#_ftplugin = ftplugin
let g:dein#_base_path = '/home/segas/dotfiles/nvim/dein/bundle'
let g:dein#_runtime_path = '/home/segas/dotfiles/nvim/dein/bundle/.cache/init.vim/.dein'
let g:dein#_cache_path = '/home/segas/dotfiles/nvim/dein/bundle/.cache/init.vim'
let &runtimepath = '/home/segas/dotfiles/nvim/dein/bundle/repos/github.com/Shougo/dein.vim/,/home/segas/.config/nvim,/etc/xdg/xdg-ubuntu/nvim,/etc/xdg/nvim,/home/segas/.local/share/nvim/site,/usr/share/ubuntu/nvim/site,/usr/local/share/nvim/site,/usr/share/nvim/site,/var/lib/snapd/desktop/nvim/site,/home/segas/dotfiles/nvim/dein/bundle/repos/github.com/Shougo/dein.vim,/home/segas/dotfiles/nvim/dein/bundle/repos/github.com/neoclide/coc.nvim_release,/home/segas/dotfiles/nvim/dein/bundle/.cache/init.vim/.dein,/usr/share/nvim/runtime,/home/segas/dotfiles/nvim/dein/bundle/.cache/init.vim/.dein/after,/var/lib/snapd/desktop/nvim/site/after,/usr/share/nvim/site/after,/usr/local/share/nvim/site/after,/usr/share/ubuntu/nvim/site/after,/home/segas/.local/share/nvim/site/after,/etc/xdg/nvim/after,/etc/xdg/xdg-ubuntu/nvim/after,/home/segas/.config/nvim/after'
filetype off
