[[plugins]]
repo = 'elzr/vim-json'
on_ft = ['json']

[[plugins]]
repo = 'leafgarland/typescript-vim'
on_ft = ['typescriptreact']

[[plugins]]
repo = 'mxw/vim-jsx'
on_ft = ['typescriptreact', 'javascript']
