# Turn on mosue
set -g mouse on


# ----- KEY BINDS -----
# Press r to reload conf
unbind t
bind t source-file ~/.config/tmux/tmux.conf

# Split window
bind s split-window -v
bind v split-window -h
bind m split-window -h -p 80 -c "#{pane_current_path}" \; split-window -h -p 25 -c "#{pane_current_path}" \; send-keys 'claude' Enter \; select-pane -L \; split-window -v -p 20 -c "#{pane_current_path}" \; select-pane -U \; send-keys 'nvim' Enter \; select-pane -t 0 \; send-keys 'lazygit' Enter \; select-pane -t 1

# Move window
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# Resize window
bind + resize-pane -U 3
bind - resize-pane -D 3
bind p resize-pane -R 10
bind o resize-pane -L 10

# Rotate wondow
bind r rotate-window

# Show last active window
bind e last-window

# Close all panes and reopen window at same path
bind X run-shell 'p="#{pane_current_path}"; tmux kill-window; tmux new-window -c "$p"'

# Interactively select window
bind \; choose-tree
bind y command-prompt -p "Stash name:" "break-pane -d -n '%1'"
# Swap current pane with selected pane
bind u choose-tree -w "swap-pane -t %%"
# bind u run-shell 'tmux break-pane -d -n "$(tmux display-message -p "#{pane_current_command}:#{b:pane_current_path}")"'

bind i choose-tree -w "join-pane -h -s %%"
bind o choose-tree -w "join-pane -s %%"

# # tmux-fuzzback
# unbind /
# set -g @fuzzback-bind /
# ----- KEY BINDS ----- end

# ----- APPEARANCE -----
# Make the status line pretty and add some modules
# set-option -g pane-active-border-style fg=colour41
set -g default-terminal "screen-256color"
set-option -ga terminal-overrides ",xterm*:Tc"

# # Status bar
set-option -g status-position top
set-option -g status-right-length 250

# ----- APPEARANCE ----- end

# ----- Plugins ----
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-pain-control'
set -g @plugin 'janoamaral/tokyo-night-tmux'
set -g @tokyo-night-tmux_show_git 0
set -g @tokyo-night-tmux_theme storm
set -g @plugin 'roosta/tmux-fuzzback' # Make sure to install fzf

run '~/.config/tmux/plugins/tpm/tpm'
# ----- Plugins ---- end
